const express = require('express');
const cors    = require('cors');
const fetch   = require('node-fetch');
const cron    = require('node-cron');

const app  = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

const NEWS_API_KEY   = process.env.NEWS_API_KEY;
const RESEND_API_KEY = process.env.RESEND_API_KEY;
const TRIGGER_SECRET = process.env.TRIGGER_SECRET || 'esg-trigger-2025';
const FROM_EMAIL     = process.env.FROM_EMAIL || 'ESG Signal <onboarding@resend.dev>';

function getAEEmails() {
  return {
    AE4:   process.env.AE4_EMAIL,
    AE5:   process.env.AE5_EMAIL,
    Dave:  process.env.DAVE_EMAIL,
    Jake:  process.env.JAKE_EMAIL,
    Jim:   process.env.JIM_EMAIL,
    Lucas: process.env.LUCAS_EMAIL,
  };
}

// ── AE COMPANY ASSIGNMENTS WITH ALIASES ──
// Each company has multiple name variants to maximise headline matching
const AE_ASSIGNMENTS = {
  "AE4": {
    companies: [
      "BlackRock",
      "Vanguard Group",
      "Fidelity Investments",
      "BNY Investments",
      "Invesco",
      "Franklin Templeton",
      "Prudential Financial",
      "T. Rowe Price Group",
      "Northern Trust",
      "Geode Capital Management",
      "Ameriprise Financial",
      "Charles Schwab Investment",
      "Blackstone",
      "Power Financial",
      "Federated Hermes",
      "Principal Financial",
      "New York Life Investments",
      "Dimensional Fund Advisors",
      "Affiliated Managers Group",
      "Allspring Global Investments",
      "MassMutual",
      "Neuberger Berman",
      "Voya Financial",
      "U.S. Bancorp",
      "Mercer",
      "Dodge & Cox",
      "SEI Investments",
      "Jackson Financial",
      "Russell Investments",
      "NISA Investment",
      "Lazard",
      "Fisher Investments",
      "Guggenheim Investments",
      "American Century",
      "Raymond James",
      "Conning",
      "Robert W. Baird",
      "TCW Group",
      "Mesirow",
      "Payden & Rygel",
      "Artisan Partners",
      "StepStone Group",
      "Massachusetts PRIM",
      "Minnesota State Board of Investment",
      "NYC Teachers Retirement System",
      "Connecticut Retirement Plans",
      "OPTrust",
      "Northern LGPS",
      "Greater Manchester Pension Fund",
      "London CIV",
      "AP1 (First AP Fund)",
      "Elo",
      "ERAFP",
      "Abu Dhabi Investment Authority (ADIA)",
      "Emirates Investment Authority",
      "Colleges of Applied Arts and Technology (CAAT)",
      "Fonds de solidarité FTQ",
      "BP Pension Fund",
      "Unilever UK Pension Fund",
      "Smart Pension",
      "Pensioenfonds Detailhandel",
      "Statens pensjonsfond Norge (GPFN)",
      "Ircantec",
      "Apicil Group",
      "KZVK (Kirchliche Zusatzversorgungskasse)",
      "Helvetia Sammelstiftung",
      "PKA",
      "Indiana Public Retirement System (INPRS)",
      "Utah Retirement Systems",
      "Oklahoma Teachers Retirement System",
      "Contra Costa County Employees Retirement Association (CCCERA)",
      "Texas Municipal Retirement System (TMRS)",
      "Pensioenfonds Huisartsen",
      "Topdanmark Pension",
      "Avanza Pension (Sweden)",
      "Debeka",
      "National Pensions Reserve Fund (NPRF successor)",
      "General Organization for Social Insurance (GOSI)",
      "Morgan Lewis",
      "Baker Botts",
      "Cravath Swaine & Moore",
      "Hunton Andrews Kurth",
      "Stephenson Harwood",
      "McCarthy Tetrault",
      "Hadef & Partners",
      "Khoshaim & Associates",
      "Freshfields Germany",
      "BSP (Bonn Steichen & Partners)",
      "South Pole",
      "Carbon Trust",
      "Frontier Economics",
      "Georgeson",
      "Drees & Sommer",
      "Bank of America",
      "First Abu Dhabi Bank",
      "National Bank of Canada",
      "Dubai Islamic Bank",
      "Nykredit",
      "KeyCorp",
    ],
    aliases: [
      "blackrock",
      "vanguard group",
      "vanguard",
      "fidelity investments",
      "fidelity",
      "bny investments",
      "invesco",
      "franklin templeton",
      "franklin",
      "prudential financial",
      "prudential",
      "t. rowe price group",
      "t. rowe price",
      "northern trust",
      "northern",
      "geode capital management",
      "geode",
      "ameriprise financial",
      "ameriprise",
      "charles schwab investment",
      "charles",
      "blackstone",
      "power financial",
      "power",
      "federated hermes",
      "federated",
      "principal financial",
      "principal",
      "new york life investments",
      "new york life",
      "dimensional fund advisors",
      "dimensional",
      "affiliated managers group",
      "affiliated managers",
      "affiliated",
      "allspring global investments",
      "allspring global",
      "allspring",
      "massmutual",
      "neuberger berman",
      "neuberger",
      "voya financial",
      "voya",
      "u.s. bancorp",
      "u.s.",
      "mercer",
      "dodge & cox",
      "dodge",
      "sei investments",
      "jackson financial",
      "jackson",
      "russell investments",
      "russell",
      "nisa investment",
      "nisa",
      "lazard",
      "fisher investments",
      "fisher",
      "guggenheim investments",
      "guggenheim",
      "american century",
      "american",
      "raymond james",
      "raymond",
      "conning",
      "robert w. baird",
      "robert",
      "tcw group",
      "mesirow",
      "payden & rygel",
      "payden",
      "artisan partners",
      "artisan",
      "stepstone group",
      "stepstone",
      "massachusetts prim",
      "massachusetts",
      "minnesota state board of investment",
      "minnesota",
      "nyc teachers retirement system",
      "connecticut retirement plans",
      "connecticut",
      "optrust",
      "northern lgps",
      "greater manchester pension fund",
      "greater",
      "london civ",
      "london",
      "ap1 (first ap fund)",
      "elo",
      "erafp",
      "abu dhabi investment authority (adia)",
      "emirates investment authority",
      "emirates",
      "colleges of applied arts and technology (caat)",
      "colleges",
      "fonds de solidarité ftq",
      "fonds",
      "bp pension fund",
      "unilever uk pension fund",
      "unilever",
      "smart pension",
      "smart",
      "pensioenfonds detailhandel",
      "pensioenfonds",
      "statens pensjonsfond norge (gpfn)",
      "statens",
      "ircantec",
      "apicil group",
      "apicil",
      "kzvk (kirchliche zusatzversorgungskasse)",
      "kzvk",
      "helvetia sammelstiftung",
      "helvetia",
      "pka",
      "indiana public retirement system (inprs)",
      "indiana",
      "utah retirement systems",
      "utah",
      "oklahoma teachers retirement system",
      "oklahoma",
      "contra costa county employees retirement association (cccera)",
      "contra",
      "texas municipal retirement system (tmrs)",
      "texas",
      "pensioenfonds huisartsen",
      "topdanmark pension",
      "topdanmark",
      "avanza pension (sweden)",
      "avanza",
      "debeka",
      "national pensions reserve fund (nprf successor)",
      "general organization for social insurance (gosi)",
      "morgan lewis",
      "morgan",
      "baker botts",
      "baker",
      "cravath swaine & moore",
      "cravath",
      "hunton andrews kurth",
      "hunton",
      "stephenson harwood",
      "stephenson",
      "mccarthy tetrault",
      "mccarthy",
      "hadef & partners",
      "hadef &",
      "hadef",
      "khoshaim & associates",
      "khoshaim",
      "freshfields germany",
      "freshfields",
      "bsp (bonn steichen & partners)",
      "south pole",
      "carbon trust",
      "carbon",
      "frontier economics",
      "frontier",
      "georgeson",
      "drees & sommer",
      "drees",
      "bank of america",
      "bank",
      "first abu dhabi bank",
      "first abu dhabi",
      "national bank of canada",
      "dubai islamic bank",
      "dubai islamic",
      "dubai",
      "nykredit",
      "keycorp",
    ],
  },
  "AE5": {
    companies: [
      "PNC Financial",
      "Virtus Investment Partners",
      "Victory Capital",
      "CBRE Investment Management",
      "PRIMECAP",
      "Hightower Advisors",
      "Starwood Capital",
      "RhumbLine Advisers",
      "Acadian",
      "TPG",
      "Thoma Bravo",
      "Warburg Pincus",
      "Apollo Global Management",
      "Oaktree Capital Management",
      "Vista Equity Partners",
      "General Atlantic",
      "Leonard Green & Partners",
      "Apogem Capital Partners",
      "TA Associates",
      "Sixth Street",
      "Insight Partners",
      "Fortress Investment Group",
      "Oak Hill Advisors",
      "Andreessen Horowitz",
      "Cerberus Capital Management",
      "American Securities",
      "Tiger Global Management",
      "BSP-Alcentra",
      "BDT & MSD Partners",
      "L Catterton",
      "Stone Point Capital",
      "Crescent Capital Group",
      "Angelo Gordon",
      "PSG",
      "KPS Capital Partners",
      "Summit Partners",
      "The Jordan Company",
      "Churchill Asset Management",
      "Lightspeed Venture Partners",
      "TSG Consumer Partners",
      "Castlelake",
      "InterVest Capital Partners",
      "Farallon Capital Management",
      "Vista Credit Partners",
      "Citigroup",
      "Emirates NBD",
      "Mashreq Bank",
      "Bunq",
      "Helaba",
      "Systemiq",
      "Cambridge Econometrics",
      "FTI Consulting (ESG)",
      "I Care & Consult",
      "K&L Gates",
      "Arnold & Porter",
      "Cahill Gordon & Reindel",
      "Simmons & Simmons",
      "Mishcon de Reya",
      "DLA Piper",
      "Stikeman Elliott",
      "King & Spalding ME",
      "Houthoff",
      "Florida State Board of Administration",
      "North Carolina Retirement",
      "Colorado PERA",
      "Illinois Teachers Retirement",
      "Los Angeles City Employees Retirement",
      "Caisse de depot et placement (CDPQ)",
      "Brunel Pension Partnership",
      "West Midlands Pension Fund",
      "PMT (Metalektro)",
      "AP2 (Second AP Fund)",
      "FRR (Fonds de Reserve)",
      "Investment Corporation of Dubai (ICD)",
      "Abu Dhabi Investment Council (ADIC)",
      "Pennsylvania Public School Employees Retirement (PSERS)",
      "Ohio State Teachers Retirement System (STRS Ohio)",
      "Missouri State Employees Retirement System (MOSERS)",
      "Delaware Public Employees Retirement System",
      "Dallas Police and Fire Pension System",
      "Marin County Employees Retirement Association (MCERA)",
      "Public Employee Retirement System of Idaho (PERSI)",
      "Alberta Teachers Retirement Fund (ATRF)",
      "Fondaction (CSN)",
      "Rolls-Royce UK Pension Fund",
      "Pearson Pension Plan",
      "Cushon",
      "Pensioenfonds Zoetwaren",
      "Pensioenfonds Vliegverkeer (PFVV)",
      "PFA Pension",
      "Skandia (Sweden)",
      "Mandatum Life (Finland)",
      "CNAV (Caisse Nationale d'Assurance Vieillesse)",
      "Agrica",
      "HUK-Coburg",
      "EZVK (Evangelische Zusatzversorgungskasse)",
      "Swiss Life Sammelstiftung",
      "Irish Life Investment Managers (ILIM)",
      "Abu Dhabi Pension Fund (ADPF)",
      "ATP",
    ],
    aliases: [
      "pnc financial",
      "virtus investment partners",
      "virtus investment",
      "virtus",
      "victory capital",
      "victory",
      "cbre investment management",
      "cbre",
      "primecap",
      "hightower advisors",
      "hightower",
      "starwood capital",
      "starwood",
      "rhumbline advisers",
      "rhumbline",
      "acadian",
      "tpg",
      "thoma bravo",
      "thoma",
      "warburg pincus",
      "warburg",
      "apollo global management",
      "apollo global",
      "apollo",
      "oaktree capital management",
      "oaktree",
      "vista equity partners",
      "vista equity",
      "vista",
      "general atlantic",
      "leonard green & partners",
      "leonard green &",
      "leonard",
      "apogem capital partners",
      "apogem",
      "ta associates",
      "sixth street",
      "sixth",
      "insight partners",
      "insight",
      "fortress investment group",
      "fortress investment",
      "fortress",
      "oak hill advisors",
      "oak hill",
      "andreessen horowitz",
      "andreessen",
      "cerberus capital management",
      "cerberus",
      "american securities",
      "american",
      "tiger global management",
      "tiger global",
      "tiger",
      "bsp-alcentra",
      "bdt & msd partners",
      "bdt & msd",
      "l catterton",
      "stone point capital",
      "stone",
      "crescent capital group",
      "crescent capital",
      "crescent",
      "angelo gordon",
      "angelo",
      "psg",
      "kps capital partners",
      "kps capital",
      "summit partners",
      "summit",
      "the jordan company",
      "churchill asset management",
      "churchill",
      "lightspeed venture partners",
      "lightspeed venture",
      "lightspeed",
      "tsg consumer partners",
      "tsg consumer",
      "castlelake",
      "intervest capital partners",
      "intervest",
      "farallon capital management",
      "farallon",
      "vista credit partners",
      "vista credit",
      "citigroup",
      "emirates nbd",
      "emirates",
      "mashreq bank",
      "mashreq",
      "bunq",
      "helaba",
      "systemiq",
      "cambridge econometrics",
      "cambridge",
      "fti consulting (esg)",
      "i care & consult",
      "k&l gates",
      "arnold & porter",
      "arnold",
      "cahill gordon & reindel",
      "cahill",
      "simmons & simmons",
      "simmons",
      "mishcon de reya",
      "mishcon",
      "dla piper",
      "stikeman elliott",
      "stikeman",
      "king & spalding me",
      "king",
      "houthoff",
      "florida state board of administration",
      "florida",
      "north carolina retirement",
      "colorado pera",
      "colorado",
      "illinois teachers retirement",
      "illinois",
      "los angeles city employees retirement",
      "caisse de depot et placement (cdpq)",
      "caisse",
      "brunel pension partnership",
      "brunel",
      "west midlands pension fund",
      "pmt (metalektro)",
      "ap2 (second ap fund)",
      "frr (fonds de reserve)",
      "investment corporation of dubai (icd)",
      "investment",
      "abu dhabi investment council (adic)",
      "pennsylvania public school employees retirement (psers)",
      "pennsylvania",
      "ohio state teachers retirement system (strs ohio)",
      "ohio",
      "missouri state employees retirement system (mosers)",
      "missouri",
      "delaware public employees retirement system",
      "delaware",
      "dallas police and fire pension system",
      "dallas",
      "marin county employees retirement association (mcera)",
      "marin",
      "public employee retirement system of idaho (persi)",
      "alberta teachers retirement fund (atrf)",
      "alberta",
      "fondaction (csn)",
      "fondaction",
      "rolls-royce uk pension fund",
      "rolls-royce",
      "pearson pension plan",
      "pearson",
      "cushon",
      "pensioenfonds zoetwaren",
      "pensioenfonds",
      "pensioenfonds vliegverkeer (pfvv)",
      "pfa pension",
      "skandia (sweden)",
      "skandia",
      "mandatum life (finland)",
      "mandatum",
      "cnav (caisse nationale d'assurance vieillesse)",
      "cnav",
      "agrica",
      "huk-coburg",
      "ezvk (evangelische zusatzversorgungskasse)",
      "ezvk",
      "swiss life sammelstiftung",
      "irish life investment managers (ilim)",
      "irish",
      "abu dhabi pension fund (adpf)",
      "atp",
    ],
  },
  "Dave": {
    companies: [
      "UBS",
      "Aegon Group",
      "Generali Group",
      "KKR",
      "Dai-ichi Life Holdings",
      "Ares Management",
      "MEAG",
      "Meiji Yasuda Life Insurance",
      "Aviva",
      "Samsung Group",
      "Banco Santander",
      "KBC Group",
      "Robeco Group",
      "WTW",
      "Talanx Group",
      "F Van Lanschot",
      "Storebrand Group",
      "Groupama Asset Management",
      "Advent International",
      "AXA IM ALTS",
      "Clearlake Capital Group",
      "Bain Capital",
      "Genstar Capital",
      "Barings",
      "New Mountain Capital",
      "Ardian",
      "HarbourVest Partners",
      "Astorg",
      "Antares Capital",
      "Hamilton Lane",
      "Eurazeo",
      "Värde Partners",
      "Morgan Stanley Investment Management",
      "Bregal Investments",
      "Park Square Capital",
    ],
    aliases: [
      "ubs",
      "aegon group",
      "aegon",
      "generali group",
      "generali",
      "kkr",
      "dai-ichi life holdings",
      "dai-ichi life",
      "dai-ichi",
      "ares management",
      "ares",
      "meag",
      "meiji yasuda life insurance",
      "meiji yasuda life",
      "meiji",
      "aviva",
      "samsung group",
      "samsung",
      "banco santander",
      "banco",
      "kbc group",
      "robeco group",
      "robeco",
      "wtw",
      "talanx group",
      "talanx",
      "f van lanschot",
      "storebrand group",
      "storebrand",
      "groupama asset management",
      "groupama",
      "advent international",
      "advent",
      "axa im alts",
      "clearlake capital group",
      "clearlake capital",
      "clearlake",
      "bain capital",
      "bain",
      "genstar capital",
      "genstar",
      "barings",
      "new mountain capital",
      "ardian",
      "harbourvest partners",
      "harbourvest",
      "astorg",
      "antares capital",
      "antares",
      "hamilton lane",
      "hamilton",
      "eurazeo",
      "värde partners",
      "värde",
      "morgan stanley investment management",
      "morgan stanley",
      "morgan",
      "bregal investments",
      "bregal",
      "park square capital",
      "park",
    ],
  },
  "Jake": {
    companies: [
      "Capital Group",
      "Allianz Group",
      "Amundi",
      "AXA Group",
      "Deutsche Bank",
      "Sumitomo Mitsui Trust Holdings",
      "HSBC Holdings",
      "Nippon Life Insurance",
      "Asset Management One",
      "LBBW",
      "M&G Investments",
      "TD Global Invest. Solutions",
      "Janus Henderson Group",
      "Swiss Life Asset Managers",
      "Zurcher Kantonalbank",
      "Zurich Financial Services",
      "St. James's Place",
      "Anima Holding Italy",
      "Royal London Group",
      "CVC Capital Partners",
      "OFI AM",
      "Caixabank",
      "Danske Bank",
      "Man Group",
      "Mn Services",
      "Partners Group",
      "ASR",
      "Bayerischen Landesbank",
      "OP Financial Group",
      "LGT Capital Partners",
      "EQT",
      "Nordic Capital",
      "Golub Capital",
      "Hayfin Capital Management",
      "Hillhouse Capital Group",
      "Accel-KKR",
      "AllianceBernstein",
      "Crestline Investors",
      "Tikehau Capital",
      "CVC Credit Partners",
      "Aberdeen Investments",
      "Lombard Odier Investment Mgmt",
      "AXA Investment Managers",
      "Wells Fargo",
      "Groupe BPCE / Natixis",
      "Saudi National Bank",
      "Truist Financial",
      "ASN Bank",
      "WSP Global",
      "Pollination",
      "2° Investing Initiative",
      "Alvarez & Marsal (ESG)",
      "Milbank",
      "Vedder Price",
      "Covington & Burling",
      "Gibson Dunn",
      "Taylor Wessing",
      "Clyde & Co",
      "Osler Hoskin & Harcourt",
      "Fasken",
      "August & Debouzy",
      "Elvinger Hoss Prussen",
      "Texas Teachers Retirement System",
      "Virginia Retirement System",
      "Michigan Retirement Systems",
      "Maryland State Retirement",
      "PSP Investments",
      "Borders to Coast Pension Partnership",
      "Strathclyde Pension Fund",
      "PME (Metaalindustrie)",
      "AP3 (Third AP Fund)",
      "Agirc-Arrco",
      "Hassana Investment (GOSI)",
      "Sanabil Investments (PIF sub)",
      "Tennessee Consolidated Retirement System",
      "Kansas Public Employees Retirement System (KPERS)",
      "Rhode Island Employees Retirement System",
      "Los Angeles Fire and Police Pensions (LAFPP)",
      "New York City Board of Education Retirement System (BERS)",
      "Wyoming Retirement System",
      "Municipal Employees Pension Plan (MEPP) Saskatchewan",
      "Pension Protection Fund (PPF)",
      "BT Pension Scheme (BTPS)",
      "National Grid UK Pension Scheme",
      "People's Partnership (The People's Pension)",
      "Pensioenfonds Horeca & Catering",
      "Stichting Pensioenfonds Openbaar Vervoer (SPOV)",
      "AP Pension",
      "Länsförsäkringar (Sweden)",
      "LocalTapiola (Finland)",
      "Préfon-Retraite",
      "DEVK Versicherungen",
      "Württembergische Versicherung (W&W Group)",
      "ASGA Pensionskasse",
      "Nest Sammelstiftung",
      "Davy Asset Management",
      "Public Pension Agency Saudi Arabia (PPA)",
    ],
    aliases: [
      "capital group",
      "capital",
      "allianz group",
      "allianz",
      "amundi",
      "axa group",
      "deutsche bank",
      "deutsche",
      "sumitomo mitsui trust holdings",
      "sumitomo mitsui trust",
      "sumitomo",
      "hsbc holdings",
      "hsbc",
      "nippon life insurance",
      "nippon life",
      "nippon",
      "asset management one",
      "asset",
      "lbbw",
      "m&g investments",
      "td global invest. solutions",
      "janus henderson group",
      "janus henderson",
      "janus",
      "swiss life asset managers",
      "swiss life",
      "zurcher kantonalbank",
      "zurcher",
      "zurich financial services",
      "zurich financial",
      "zurich",
      "st. james's place",
      "anima holding italy",
      "anima",
      "royal london group",
      "royal london",
      "royal",
      "cvc capital partners",
      "cvc capital",
      "ofi am",
      "caixabank",
      "danske bank",
      "danske",
      "man group",
      "mn services",
      "partners group",
      "partners",
      "asr",
      "bayerischen landesbank",
      "bayerischen",
      "op financial group",
      "op financial",
      "lgt capital partners",
      "lgt capital",
      "eqt",
      "nordic capital",
      "nordic",
      "golub capital",
      "golub",
      "hayfin capital management",
      "hayfin",
      "hillhouse capital group",
      "hillhouse capital",
      "hillhouse",
      "accel-kkr",
      "alliancebernstein",
      "crestline investors",
      "crestline",
      "tikehau capital",
      "tikehau",
      "cvc credit partners",
      "cvc credit",
      "aberdeen investments",
      "aberdeen",
      "lombard odier investment mgmt",
      "lombard",
      "axa investment managers",
      "wells fargo",
      "wells",
      "groupe bpce / natixis",
      "groupe",
      "saudi national bank",
      "saudi national",
      "saudi",
      "truist financial",
      "truist",
      "asn bank",
      "wsp global",
      "pollination",
      "2° investing initiative",
      "alvarez & marsal (esg)",
      "alvarez",
      "milbank",
      "vedder price",
      "vedder",
      "covington & burling",
      "covington",
      "gibson dunn",
      "gibson",
      "taylor wessing",
      "taylor",
      "clyde & co",
      "clyde",
      "osler hoskin & harcourt",
      "osler",
      "fasken",
      "august & debouzy",
      "august",
      "elvinger hoss prussen",
      "elvinger",
      "texas teachers retirement system",
      "texas",
      "virginia retirement system",
      "virginia",
      "michigan retirement systems",
      "michigan",
      "maryland state retirement",
      "maryland",
      "psp investments",
      "borders to coast pension partnership",
      "borders",
      "strathclyde pension fund",
      "strathclyde",
      "pme (metaalindustrie)",
      "ap3 (third ap fund)",
      "agirc-arrco",
      "hassana investment (gosi)",
      "hassana",
      "sanabil investments (pif sub)",
      "sanabil",
      "tennessee consolidated retirement system",
      "tennessee",
      "kansas public employees retirement system (kpers)",
      "kansas",
      "rhode island employees retirement system",
      "rhode",
      "los angeles fire and police pensions (lafpp)",
      "new york city board of education retirement system (bers)",
      "wyoming retirement system",
      "wyoming",
      "municipal employees pension plan (mepp) saskatchewan",
      "municipal",
      "pension protection fund (ppf)",
      "pension",
      "bt pension scheme (btps)",
      "national grid uk pension scheme",
      "people's partnership (the people's pension)",
      "people's",
      "pensioenfonds horeca & catering",
      "pensioenfonds",
      "stichting pensioenfonds openbaar vervoer (spov)",
      "stichting",
      "ap pension",
      "länsförsäkringar (sweden)",
      "länsförsäkringar",
      "localtapiola (finland)",
      "localtapiola",
      "préfon-retraite",
      "devk versicherungen",
      "devk",
      "württembergische versicherung (w&w group)",
      "württembergische",
      "asga pensionskasse",
      "asga",
      "nest sammelstiftung",
      "nest",
      "davy asset management",
      "davy",
      "public pension agency saudi arabia (ppa)",
    ],
  },
  "Jim": {
    companies: [
      "State Street Global",
      "BNP Paribas",
      "Natixis Investment Managers",
      "Nuveen",
      "Brookfield Asset Management",
      "Manulife",
      "Mitsubishi UFJ Financial Group",
      "Macquarie Group",
      "Union Investment",
      "Intesa Sanpaolo",
      "Abrdn",
      "Zenkyoren",
      "Shinkin Central Bank",
      "Baillie Gifford",
      "Pictet Asset Management",
      "BMO Wealth Management",
      "Scotiabank",
      "SEB",
      "Resona Holdings",
      "Landesbank Hessen-Thuringen",
      "EFG International",
      "BBVA",
      "IFM Investors",
      "BCV",
      "Mirae Asset Financial Group",
      "Aon",
      "IDUNA Gruppe",
      "Goldman Sachs Asset Management",
      "HPS Investment Partners",
      "The Carlyle Group",
      "Clayton Dubilier & Rice",
      "Silver Lake",
      "Pacific Investment Management Company",
      "Permira Advisers",
      "Cinven",
      "Blue Owl Capital",
      "Bridgepoint",
      "Pemberton Asset Management",
      "PAG",
      "TCV",
      "MBK Partners",
      "Liontrust",
      "Sarasin & Partners",
      "Sycomore Asset Management",
      "DWS Group",
      "Toronto-Dominion Bank",
      "DZ Bank",
      "Al Rajhi Bank",
      "SpareBank 1",
      "Belfius",
      "Anthesis Group",
      "Quantis",
      "L.E.K. Consulting",
      "Charles River Associates",
      "Fried Frank",
      "Winston & Strawn",
      "Akin Gump",
      "Seward & Kissel",
      "Burges Salmon",
      "HFW (Holman Fenwick Willan)",
      "Blake Cassels & Graydon",
      "Gowling WLG",
      "Joffe & Associes",
      "Arendt & Medernach",
      "Wisconsin Investment Board",
      "Oregon Investment Council",
      "PSERS Pennsylvania",
      "Arizona State Retirement",
      "BT Pension Scheme",
      "ACCESS Pool",
      "Lothian Pension Fund",
      "bpfBOUW",
      "AP4 (Fourth AP Fund)",
      "Bayerische Versorgungskammer (BVK)",
      "Oman Investment Authority (OIA)",
      "Georgia Teachers Retirement System",
      "Montana Board of Investments",
      "Maine Public Employees Retirement System (MainePERS)",
      "San Diego City Employees Retirement System (SDCERS)",
      "Illinois Municipal Retirement Fund (IMRF)",
      "Vermont Pension Investment Committee (VPIC)",
      "Manitoba Teachers' Society Pension Plan",
      "National Employment Savings Trust (NEST)",
      "Sainsbury's Pension Scheme",
      "Centrica Pension Scheme",
      "NOW: Pensions",
      "Pensioenfonds Vervoer",
      "Kommunal Landspensjonskasse (KLP)",
      "Sampension",
      "Fjärde AP-fonden (AP4)",
      "Malakoff Humanis",
      "Pro BTP",
      "Signal Iduna",
      "Provinzial Rheinland",
      "Pensionskasse der Swisscom",
      "Ethos Foundation / Ethos Services",
      "Ethias",
      "Social Insurance Investment Portfolio (Bahrain)",
    ],
    aliases: [
      "state street global",
      "state street",
      "bnp paribas",
      "natixis investment managers",
      "natixis",
      "nuveen",
      "brookfield asset management",
      "brookfield",
      "manulife",
      "mitsubishi ufj financial group",
      "mitsubishi ufj financial",
      "mitsubishi",
      "macquarie group",
      "macquarie",
      "union investment",
      "union",
      "intesa sanpaolo",
      "intesa",
      "abrdn",
      "zenkyoren",
      "shinkin central bank",
      "shinkin central",
      "shinkin",
      "baillie gifford",
      "baillie",
      "pictet asset management",
      "pictet",
      "bmo wealth management",
      "bmo wealth",
      "scotiabank",
      "seb",
      "resona holdings",
      "resona",
      "landesbank hessen-thuringen",
      "landesbank",
      "efg international",
      "bbva",
      "ifm investors",
      "bcv",
      "mirae asset financial group",
      "mirae asset financial",
      "mirae",
      "aon",
      "iduna gruppe",
      "iduna",
      "goldman sachs asset management",
      "goldman sachs",
      "goldman",
      "hps investment partners",
      "hps investment",
      "the carlyle group",
      "the carlyle",
      "clayton dubilier & rice",
      "clayton",
      "silver lake",
      "silver",
      "pacific investment management company",
      "pacific",
      "permira advisers",
      "permira",
      "cinven",
      "blue owl capital",
      "blue",
      "bridgepoint",
      "pemberton asset management",
      "pemberton",
      "pag",
      "tcv",
      "mbk partners",
      "liontrust",
      "sarasin & partners",
      "sarasin &",
      "sarasin",
      "sycomore asset management",
      "sycomore",
      "dws group",
      "toronto-dominion bank",
      "toronto-dominion",
      "dz bank",
      "al rajhi bank",
      "al rajhi",
      "sparebank 1",
      "sparebank",
      "belfius",
      "anthesis group",
      "anthesis",
      "quantis",
      "l.e.k. consulting",
      "l.e.k.",
      "charles river associates",
      "charles",
      "fried frank",
      "fried",
      "winston & strawn",
      "winston",
      "akin gump",
      "akin",
      "seward & kissel",
      "seward",
      "burges salmon",
      "burges",
      "hfw (holman fenwick willan)",
      "blake cassels & graydon",
      "blake",
      "gowling wlg",
      "gowling",
      "joffe & associes",
      "joffe",
      "arendt & medernach",
      "arendt",
      "wisconsin investment board",
      "wisconsin",
      "oregon investment council",
      "oregon",
      "psers pennsylvania",
      "psers",
      "arizona state retirement",
      "arizona",
      "bt pension scheme",
      "access pool",
      "access",
      "lothian pension fund",
      "lothian",
      "bpfbouw",
      "ap4 (fourth ap fund)",
      "bayerische versorgungskammer (bvk)",
      "bayerische",
      "oman investment authority (oia)",
      "oman",
      "georgia teachers retirement system",
      "georgia",
      "montana board of investments",
      "montana board of",
      "montana",
      "maine public employees retirement system (mainepers)",
      "maine",
      "san diego city employees retirement system (sdcers)",
      "illinois municipal retirement fund (imrf)",
      "illinois",
      "vermont pension investment committee (vpic)",
      "vermont",
      "manitoba teachers' society pension plan",
      "manitoba",
      "national employment savings trust (nest)",
      "sainsbury's pension scheme",
      "sainsbury's",
      "centrica pension scheme",
      "centrica",
      "now: pensions",
      "now:",
      "pensioenfonds vervoer",
      "pensioenfonds",
      "kommunal landspensjonskasse (klp)",
      "kommunal",
      "sampension",
      "fjärde ap-fonden (ap4)",
      "fjärde",
      "malakoff humanis",
      "malakoff",
      "pro btp",
      "signal iduna",
      "signal",
      "provinzial rheinland",
      "provinzial",
      "pensionskasse der swisscom",
      "pensionskasse",
      "ethos foundation / ethos services",
      "ethos foundation / ethos",
      "ethos",
      "ethias",
      "social insurance investment portfolio (bahrain)",
      "social",
    ],
  },
  "Lucas": {
    companies: [
      "J.P. Morgan Chase",
      "Legal & General Group",
      "Wellington Management",
      "Sun Life Financial",
      "Schroders",
      "Fidelity International",
      "Royal Bank of Canada",
      "Nomura Asset Management",
      "Credit Suisse",
      "Nordea",
      "Societe Generale",
      "Prudential",
      "Dekabank Group",
      "Sumitomo Life Insurance",
      "CIBC Asset Management",
      "Achmea",
      "Swedbank",
      "Union Bancaire Privee",
      "Vontobel Asset Management",
      "Credit Mutuel",
      "Sumitomo Mitsui Financial Group",
      "Rothschild",
      "Swiss Re",
      "KB Asset Management",
      "Svenska Handelsbanken",
      "Hg",
      "Intermediate Capital Group",
      "Hellman & Friedman",
      "PGIM Private Alternatives",
      "Francisco Partners",
      "GTCR",
      "Platinum Equity",
      "Adams Street Partners",
      "Arcmont Asset Management",
      "Veritas Capital",
      "Apax Partners",
      "GoldenTree Asset Management",
      "Thomas H. Lee Partners",
      "PAI Partners",
      "EIG",
      "Albacore Capital Group",
      "IK Partners",
      "Altor Equity Partners",
      "Carmignac",
      "Flossbach von Storch",
      "Bank of Nova Scotia",
      "KfW",
      "Abu Dhabi Commercial Bank",
      "Jyske Bank",
      "Fifth Third Bancorp",
      "DNV",
      "Vivid Economics (McKinsey)",
      "Morrow Sodali",
      "Strategy& (PwC)",
      "Cornerstone Research",
      "Schulte Roth & Zabel",
      "Vinson & Elkins",
      "Shearman & Sterling (A&O Shearman)",
      "Troutman Pepper",
      "Bird & Bird",
      "Reed Smith",
      "Bennett Jones",
      "Al Tamimi & Company",
      "Al Busaidy Mansoor Jamal",
      "Fidal",
      "Wildgen",
      "New Jersey Division of Investment",
      "Ohio Public Employees Retirement",
      "NYC Employees Retirement System",
      "Iowa Public Employees Retirement",
      "Investment Management Corp Ontario (IMCO)",
      "LGPS Central",
      "LGPS Wales (Wales Pension Partnership)",
      "London Pensions Fund Authority (LPFA)",
      "PFZW",
      "Keva",
      "Caisse des Dépôts",
      "VBL (Versorgungsanstalt)",
      "Mumtalakat (Bahrain)",
      "South Carolina Retirement System",
      "Nevada Public Employees Retirement System (NVPERS)",
      "New Hampshire Retirement System",
      "Sacramento County Employees' Retirement System (SCERS)",
      "Chicago Teachers Pension Fund (CTPF)",
      "CAAT Pension Plan",
      "Régime de retraite du personnel d'encadrement (RRPE)",
      "Shell Contributory Pension Fund",
      "Marks & Spencer Pension Scheme",
      "Tesco PLC Pension Scheme",
      "Scottish Widows Master Trust",
      "Pensioenfonds Medisch Specialisten",
      "Statens pensjonsfond utland (GPFG / Oil Fund)",
      "Lærernes Pension (LP)",
      "SPP Fonder",
      "AG2R La Mondiale",
      "Klesia",
      "R+V Versicherung",
      "Sparkassen-Versicherung",
      "Bâloise (Baloise Sammelstiftung)",
      "Ireland Strategic Investment Fund (ISIF)",
      "Integrale",
      "Goodwin Procter",
      "Squire Patton Boggs",
      "CMS Francis Lefebvre",
      "Kohlberg & Company",
      "MetLife Investment Management",
      "H.I.G. Capital",
      "Fiera Capital",
      "Desjardins Group",
      "Healthcare of Ontario Pension (HOOPP)",
    ],
    aliases: [
      "j.p. morgan chase",
      "legal & general group",
      "legal & general",
      "wellington management",
      "wellington",
      "sun life financial",
      "sun life",
      "schroders",
      "fidelity international",
      "fidelity",
      "royal bank of canada",
      "royal",
      "nomura asset management",
      "nomura",
      "credit suisse",
      "credit",
      "nordea",
      "societe generale",
      "societe",
      "prudential",
      "dekabank group",
      "dekabank",
      "sumitomo life insurance",
      "sumitomo life",
      "sumitomo",
      "cibc asset management",
      "cibc",
      "achmea",
      "swedbank",
      "union bancaire privee",
      "union",
      "vontobel asset management",
      "vontobel",
      "credit mutuel",
      "sumitomo mitsui financial group",
      "sumitomo mitsui financial",
      "rothschild",
      "swiss re",
      "kb asset management",
      "kb asset",
      "svenska handelsbanken",
      "svenska",
      "intermediate capital group",
      "intermediate capital",
      "intermediate",
      "hellman & friedman",
      "hellman",
      "pgim private alternatives",
      "pgim",
      "francisco partners",
      "francisco",
      "gtcr",
      "platinum equity",
      "platinum",
      "adams street partners",
      "adams street",
      "adams",
      "arcmont asset management",
      "arcmont",
      "veritas capital",
      "veritas",
      "apax partners",
      "apax",
      "goldentree asset management",
      "goldentree",
      "thomas h. lee partners",
      "thomas h. lee",
      "thomas",
      "pai partners",
      "eig",
      "albacore capital group",
      "albacore capital",
      "albacore",
      "ik partners",
      "altor equity partners",
      "altor equity",
      "altor",
      "carmignac",
      "flossbach von storch",
      "flossbach",
      "bank of nova scotia",
      "bank",
      "kfw",
      "abu dhabi commercial bank",
      "abu dhabi commercial",
      "jyske bank",
      "jyske",
      "fifth third bancorp",
      "fifth",
      "dnv",
      "vivid economics (mckinsey)",
      "vivid",
      "morrow sodali",
      "morrow",
      "strategy& (pwc)",
      "strategy&",
      "cornerstone research",
      "cornerstone",
      "schulte roth & zabel",
      "schulte",
      "vinson & elkins",
      "vinson",
      "shearman & sterling (a&o shearman)",
      "shearman",
      "troutman pepper",
      "troutman",
      "bird & bird",
      "bird",
      "reed smith",
      "reed",
      "bennett jones",
      "bennett",
      "al tamimi & company",
      "al busaidy mansoor jamal",
      "fidal",
      "wildgen",
      "new jersey division of investment",
      "ohio public employees retirement",
      "ohio",
      "nyc employees retirement system",
      "iowa public employees retirement",
      "iowa",
      "investment management corp ontario (imco)",
      "investment",
      "lgps central",
      "lgps",
      "lgps wales (wales pension partnership)",
      "london pensions fund authority (lpfa)",
      "london",
      "pfzw",
      "keva",
      "caisse des dépôts",
      "caisse",
      "vbl (versorgungsanstalt)",
      "mumtalakat (bahrain)",
      "mumtalakat",
      "south carolina retirement system",
      "nevada public employees retirement system (nvpers)",
      "nevada",
      "new hampshire retirement system",
      "sacramento county employees' retirement system (scers)",
      "sacramento",
      "chicago teachers pension fund (ctpf)",
      "chicago",
      "caat pension plan",
      "caat",
      "régime de retraite du personnel d'encadrement (rrpe)",
      "régime",
      "shell contributory pension fund",
      "shell",
      "marks & spencer pension scheme",
      "marks",
      "tesco plc pension scheme",
      "tesco",
      "scottish widows master trust",
      "scottish",
      "pensioenfonds medisch specialisten",
      "pensioenfonds",
      "statens pensjonsfond utland (gpfg / oil fund)",
      "statens",
      "lærernes pension (lp)",
      "lærernes",
      "spp fonder",
      "ag2r la mondiale",
      "ag2r",
      "klesia",
      "r+v versicherung",
      "sparkassen-versicherung",
      "bâloise (baloise sammelstiftung)",
      "bâloise",
      "ireland strategic investment fund (isif)",
      "ireland",
      "integrale",
      "goodwin procter",
      "goodwin",
      "squire patton boggs",
      "squire",
      "cms francis lefebvre",
      "kohlberg & company",
      "kohlberg",
      "metlife investment management",
      "metlife",
      "h.i.g. capital",
      "h.i.g.",
      "fiera capital",
      "fiera",
      "desjardins group",
      "desjardins",
      "healthcare of ontario pension (hoopp)",
      "healthcare",
    ],
  },
};


// ── ESG TRIGGER KEYWORDS (your proven Google Alerts format) ──
const ESG_TRIGGER_KEYWORDS = [
  'new fund','fund launch','new strategy','secondaries','secondary fund',
  'growing alternatives','alternative investment','growing credit','private credit',
  'growing private equity','growing private markets','impact fund','impact investing',
  'article 8','article 9','sfdr','tcfd','csrd','sdg','un sdg',
  'new sustainability leadership','head of esg','chief sustainability officer',
  'sustainability director','head of responsible investment',
  'sustainable investment','responsible investment','esg strategy',
  'esg commitment','esg framework','esg report','esg rating','esg score',
  'net zero','net-zero','carbon neutral','decarboni','climate finance',
  'green bond','social bond','sustainability bond','impact bond',
  'stewardship','shareholder engagement','proxy voting',
  'science based target','sbti','paris agreement',
  'scope 1','scope 2','scope 3','biodiversity','nature positive',
  'esg','environmental social','sustainability report',
  'responsible finance','climate risk','esg data',
];

// ── WIDER NEWS QUERIES — more queries = more articles scanned ──
// Using your proven format: company-type + ESG trigger terms
const DIGEST_QUERIES = [
  '"new fund" OR "impact fund" OR "Article 8" OR "Article 9" ESG',
  '"responsible investment" OR "sustainable investment" finance',
  '"head of ESG" OR "chief sustainability" OR "sustainability director"',
  '"secondaries" OR "private credit" OR "private equity" ESG sustainability',
  '"net zero" OR "carbon neutral" investment fund finance',
  '"SFDR" OR "TCFD" OR "CSRD" asset manager',
  '"SDG" OR "stewardship" OR "shareholder engagement" investment',
  '"ESG rating" OR "ESG score" OR "ESG report" financial',
  '"green bond" OR "social bond" OR "impact bond" issued',
  '"ESG strategy" OR "ESG commitment" OR "ESG framework" fund',
  'sustainability "private equity" OR "asset management" OR "pension"',
  '"responsible investment" OR "impact investing" 2025 2026',
];

app.get('/', (_req, res) => {
  const emails = getAEEmails();
  res.json({
    status: 'ESG Signal proxy OK',
    schedule: 'Daily digest at 07:00 UTC (12:30 PM IST)',
    ae_assignments: Object.fromEntries(
      Object.entries(AE_ASSIGNMENTS).map(([ae,data])=>[ae,{
        companies: data.companies.length,
        aliases: data.aliases.length,
        email: emails[ae] ? 'configured' : 'not set yet'
      }])
    ),
    time: new Date().toISOString()
  });
});

app.get('/news', async (req, res) => {
  if (!NEWS_API_KEY) return res.status(500).json({ error: 'NEWS_API_KEY not set' });
  const { q, pageSize = '10', from } = req.query;
  if (!q) return res.status(400).json({ error: 'Missing q' });
  try {
    const params = new URLSearchParams({ q, language:'en', pageSize, sortBy:'publishedAt', apiKey:NEWS_API_KEY });
    if (from) params.append('from', from);
    const r = await fetch(`https://newsapi.org/v2/everything?${params}`);
    const d = await r.json();
    if (d.status === 'error') return res.status(400).json({ error: d.message });
    res.json(d);
  } catch (err) { res.status(500).json({ error: err.message }); }
});

app.get('/trigger-digest', async (req, res) => {
  if (req.query.secret !== TRIGGER_SECRET) return res.status(401).json({ error: 'Wrong secret' });
  const ae = req.query.ae || 'all';
  res.json({ message: `Digest triggered for "${ae}" — check email in ~2 minutes` });
  runDailyDigest(ae);
});

// ════════════════════════════════
//  FETCH LAST 24H NEWS
// ════════════════════════════════
async function fetchAllNews() {
  const from = new Date(Date.now()-24*60*60*1000).toISOString().split('T')[0];
  const allArticles = [];

  for (const query of DIGEST_QUERIES) {
    try {
      const params = new URLSearchParams({
        q: query, language:'en', pageSize:'10',
        sortBy:'publishedAt', from, apiKey:NEWS_API_KEY
      });
      const r = await fetch(`https://newsapi.org/v2/everything?${params}`);
      const d = await r.json();
      if (d.articles) allArticles.push(...d.articles);
      await new Promise(r=>setTimeout(r,300));
    } catch(e) { console.error(`Query failed: ${query}`, e.message); }
  }

  // Deduplicate
  const seen = new Set();
  const unique = allArticles.filter(a=>{
    if (!a.title||a.title==='[Removed]'||!a.url||seen.has(a.url)) return false;
    seen.add(a.url); return true;
  });
  console.log(`Fetched ${unique.length} unique articles from ${DIGEST_QUERIES.length} queries`);
  return unique;
}

// ════════════════════════════════
//  MATCH FOR ONE AE
//  Uses aliases for better matching
// ════════════════════════════════
function matchForAE(articles, aeData) {
  const matches = [];
  for (const article of articles) {
    const text = ((article.title||'')+'|'+(article.description||'')+'|'+(article.content||'')).toLowerCase();

    // Must match ESG trigger keyword
    const esgMatch = ESG_TRIGGER_KEYWORDS.find(kw=>text.includes(kw.toLowerCase()));
    if (!esgMatch) continue;

    // Check full company names first (most specific)
    let companyMatch = aeData.companies.find(co=>text.includes(co.toLowerCase()));

    // If no exact match, try aliases (shorter names)
    if (!companyMatch) {
      const aliasMatch = aeData.aliases.find(alias=>
        alias.length > 3 && text.includes(alias.toLowerCase())
      );
      if (aliasMatch) {
        // Find which full company this alias belongs to
        companyMatch = aeData.companies.find(co=>
          co.toLowerCase().includes(aliasMatch) || aliasMatch.includes(co.toLowerCase().split(' ')[0])
        ) || aliasMatch;
      }
    }

    if (!companyMatch) continue;

    // Avoid duplicates — same article matched for same company
    const dupKey = `${article.url}|${companyMatch}`;
    if (matches.find(m=>`${m.url}|${m._company}`===dupKey)) continue;

    matches.push({ ...article, _trigger: esgMatch, _company: companyMatch });
  }
  return matches.sort((a,b)=>a._company.localeCompare(b._company));
}

// ════════════════════════════════
//  BUILD EMAIL HTML
// ════════════════════════════════
function buildEmail(aeName, matches, totalCompanies) {
  const dateStr = new Date().toLocaleDateString('en-GB',{
    weekday:'long', day:'numeric', month:'long', year:'numeric'
  });

  const header = `
    <div style="background:#0d1421;padding:22px 28px;border-radius:10px 10px 0 0;">
      <h1 style="color:#10d4a8;margin:0 0 3px;font-size:20px;font-family:sans-serif;">◈ ESG Signal</h1>
      <p style="color:#8ba0bc;margin:0;font-size:12px;font-family:sans-serif;">
        Daily Digest · ${dateStr} · ${aeName}'s accounts (${totalCompanies} companies)
      </p>
    </div>`;

  if (matches.length === 0) {
    return `<div style="max-width:620px;margin:0 auto;font-family:sans-serif;">
      ${header}
      <div style="background:#fff;border:1px solid #e5e7eb;border-top:none;border-radius:0 0 10px 10px;padding:24px 28px;">
        <p style="color:#6b7280;font-size:14px;margin:0;line-height:1.6;">
          No ESG or sustainability triggers found for your ${totalCompanies} accounts in the last 24 hours.<br><br>
          Check back tomorrow or open the <a href="https://rasikapinglikar-debug.github.io/esg-signal" style="color:#10d4a8;">ESG Signal tool</a> to search any company manually.
        </p>
      </div>
    </div>`;
  }

  const cards = matches.map(a=>`
    <div style="border:1px solid #e5e7eb;border-radius:8px;padding:16px;margin-bottom:12px;border-left:4px solid #10d4a8;background:#fff;">
      <div style="margin-bottom:8px;">
        <span style="background:#d1fae5;color:#065f46;padding:2px 9px;border-radius:20px;font-size:11px;font-weight:700;font-family:sans-serif;">
          🏢 ${a._company}
        </span>
        <span style="background:#ede9fe;color:#5b21b6;padding:2px 9px;border-radius:20px;font-size:11px;font-family:sans-serif;margin-left:5px;">
          🔑 ${a._trigger}
        </span>
      </div>
      <h3 style="margin:0 0 6px;font-size:15px;color:#111;font-family:sans-serif;line-height:1.4;">
        <a href="${a.url}" style="color:#111;text-decoration:none;">${a.title}</a>
      </h3>
      <p style="margin:0 0 12px;font-size:13px;color:#555;line-height:1.5;font-family:sans-serif;">
        ${a.description||''}
      </p>
      <div style="display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:6px;">
        <span style="font-size:12px;color:#9ca3af;font-family:sans-serif;">
          📰 ${a.source?.name||'Unknown'} · ${new Date(a.publishedAt).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}
        </span>
        <a href="${a.url}" style="background:#10d4a8;color:#fff;padding:6px 14px;border-radius:6px;font-size:12px;text-decoration:none;font-weight:600;font-family:sans-serif;">
          Read article →
        </a>
      </div>
    </div>`).join('');

  return `
  <div style="max-width:620px;margin:0 auto;font-family:sans-serif;background:#f9fafb;padding:16px;">
    ${header}
    <div style="background:#fff;border:1px solid #e5e7eb;border-top:none;padding:16px 28px 12px;">
      <p style="margin:0;font-size:14px;color:#374151;font-family:sans-serif;">
        🎯 <strong style="color:#10d4a8;">${matches.length} ESG trigger${matches.length>1?'s':''}</strong>
        found across your ${totalCompanies} accounts in the last 24 hours.
      </p>
    </div>
    <div style="padding:16px 0;">
      ${cards}
    </div>
    <div style="text-align:center;padding:16px;color:#9ca3af;font-size:11px;font-family:sans-serif;border-top:1px solid #e5e7eb;">
      ESG Signal · Personalised for ${aeName} · Verified articles via NewsAPI · Always verify before outreach<br><br>
      <a href="https://rasikapinglikar-debug.github.io/esg-signal" style="color:#10d4a8;text-decoration:none;">Open ESG Signal Tool →</a>
    </div>
  </div>`;
}

// ════════════════════════════════
//  SEND EMAIL
// ════════════════════════════════
async function sendEmail(toEmail, aeName, matches, totalCompanies) {
  if (!RESEND_API_KEY||!toEmail) return;
  const dateStr = new Date().toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});
  const subject = matches.length > 0
    ? `🌿 ESG Signal [${aeName}]: ${matches.length} trigger${matches.length>1?'s':''} today — ${dateStr}`
    : `ESG Signal [${aeName}]: No triggers today — ${dateStr}`;
  try {
    const r = await fetch('https://api.resend.com/emails',{
      method:'POST',
      headers:{'Content-Type':'application/json','Authorization':`Bearer ${RESEND_API_KEY}`},
      body:JSON.stringify({ from:FROM_EMAIL, to:[toEmail], subject, html:buildEmail(aeName,matches,totalCompanies) })
    });
    const d = await r.json();
    if (d.id) console.log(`✅ Sent to ${aeName} (${toEmail}): ${matches.length} matches`);
    else console.error(`❌ Failed for ${aeName}:`, JSON.stringify(d));
  } catch(e) { console.error(`❌ Email error for ${aeName}:`, e.message); }
}

// ════════════════════════════════
//  MAIN DIGEST RUNNER
// ════════════════════════════════
async function runDailyDigest(target='all') {
  console.log(`[${new Date().toISOString()}] Running digest — target: ${target}`);
  const emails = getAEEmails();
  try {
    const articles = await fetchAllNews();
    const aesToRun = target==='all' ? Object.keys(AE_ASSIGNMENTS) : [target].filter(ae=>AE_ASSIGNMENTS[ae]);

    for (const ae of aesToRun) {
      const email = emails[ae];
      if (!email) { console.log(`⏭ Skipping ${ae} — no email set`); continue; }
      const matches = matchForAE(articles, AE_ASSIGNMENTS[ae]);
      console.log(`${ae}: ${matches.length} matches from ${AE_ASSIGNMENTS[ae].companies.length} companies`);
      matches.forEach(m=>console.log(`   → ${m._company} | ${m._trigger} | ${m.title.substring(0,55)}`));
      await sendEmail(email, ae, matches, AE_ASSIGNMENTS[ae].companies.length);
      await new Promise(r=>setTimeout(r,500));
    }

    // Manager gets all matches combined
    const managerEmail = process.env.MANAGER_EMAIL;
    if (managerEmail && target==='all') {
      const allMatches = [];
      const seen = new Set();
      for (const ae of Object.keys(AE_ASSIGNMENTS)) {
        for (const m of matchForAE(articles, AE_ASSIGNMENTS[ae])) {
          if (!seen.has(m.url)) { seen.add(m.url); allMatches.push({...m, _ae:ae}); }
        }
      }
      console.log(`Manager: ${allMatches.length} total unique matches`);
      await sendEmail(managerEmail, 'Manager (All AEs)', allMatches, 539);
    }
  } catch(e) { console.error('Digest error:', e.message); }
}

// ════════════════════════════════
//  SCHEDULE: 07:00 UTC daily
//  = 12:30 PM IST / 08:00 BST
// ════════════════════════════════
cron.schedule('0 7 * * *', ()=>{
  console.log('⏰ Cron: daily digest');
  runDailyDigest('all');
}, { timezone:'UTC' });

console.log(`✅ ESG Signal proxy on port ${PORT}`);
console.log(`✅ Daily digest: 07:00 UTC (12:30 PM IST)`);
console.log(`✅ AEs: ${Object.keys(AE_ASSIGNMENTS).join(', ')}`);
console.log(`✅ Companies: ${Object.values(AE_ASSIGNMENTS).reduce((s,d)=>s+d.companies.length,0)}`);
console.log(`✅ Queries: ${12} (wider coverage for better matching)`);

app.listen(PORT,()=>{});
